samples:
 G1: /data/pathogens/acinetobacter_baumannii_acicu.fasta
 G2: /data/pathogens/aeromonas_hydrophila_ml09119.fasta
 G3: /data/pathogens/aeromonas_hydrophila_subsp_hydrophila_atcc_7966.fasta
 G4: /data/pathogens/aeromonas_salmonicida_subsp_salmonicida_a449.fasta
 G5: /data/pathogens/aeromonas_veronii_b565.fasta
 G6: /data/pathogens/anaplasma_phagocytophilum_hz.fasta
 G7: /data/pathogens/bacillus_anthracis.fasta
 G8: /data/pathogens/bacillus_anthracis_str_ames_ancestor.fasta
 G9: /data/pathogens/bacillus_anthracis_str_sterne.fasta
 G10: /data/pathogens/bacillus_cereus_atcc_10987.fasta
 G11: /data/pathogens/bacillus_cereus_atcc_14579.fasta
 G12: /data/pathogens/bacillus_subtilis_subsp_subtilis_str_168.fasta
 G13: /data/pathogens/bartonella_henselae_str_houston1.fasta
 G14: /data/pathogens/bartonella_quintana_str_toulouse.fasta
 G15: /data/pathogens/bordetella_pertussis_tohama_i.fasta
 G16: /data/pathogens/brucella_melitensis_bv_1_str_16m.fasta
 G17: /data/pathogens/brucella_suis_1330.fasta
 G18: /data/pathogens/burkholderia_pseudomallei_k96243.fasta
 G19: /data/pathogens/campylobacter_jejuni_subsp_jejuni_81176.fasta
 G20: /data/pathogens/campylobacter_jejuni_subsp_jejuni_nctc_11168.fasta
 G21: /data/pathogens/chlamydia_trachomatis_duw3cx.fasta
 G22: /data/pathogens/clostridium_botulinum_d_str_1873.fasta
 G23: /data/pathogens/clostridium_difficile_630.fasta
 G24: /data/pathogens/clostridium_perfringens_atcc_13124.fasta
 G25: /data/pathogens/clostridium_perfringens_b_str_atcc_3626.fasta
 G26: /data/pathogens/clostridium_perfringens_sm101.fasta
 G27: /data/pathogens/clostridium_perfringens_str_13.fasta
 G28: /data/pathogens/clostridium_perfringens_str_nctc_8533b4d.fasta
 G29: /data/pathogens/clostridium_tetani_e88.fasta
 G30: /data/pathogens/corynebacterium_diphtheriae_nctc_13129.fasta
 G31: /data/pathogens/coxiella_burnetii_cbugq212.fasta
 G32: /data/pathogens/coxiella_burnetii_cbukq154.fasta
 G33: /data/pathogens/coxiella_burnetii_dugway_5j108111.fasta
 G34: /data/pathogens/coxiella_burnetii_rsa_331.fasta
 G35: /data/pathogens/coxiella_burnetii_rsa_493.fasta
 G36: /data/pathogens/enterococcus_faecalis_v583.fasta
 G37: /data/pathogens/enterococcus_faecium_do.fasta
 G38: /data/pathogens/escherichia_coli.fasta
 G39: /data/pathogens/escherichia_coli_55989.fasta
 G40: /data/pathogens/escherichia_coli_b171.fasta
 G41: /data/pathogens/escherichia_coli_c34262.fasta
 G42: /data/pathogens/escherichia_coli_cft073.fasta
 G43: /data/pathogens/escherichia_coli_se11.fasta
 G44: /data/pathogens/escherichia_coli_str_042.fasta
 G45: /data/pathogens/escherichia_coli_str_111kh86.fasta
 G46: /data/pathogens/escherichia_coli_uti89.fasta
 G47: /data/pathogens/haemophilus_influenzae_rd_kw20.fasta
 G48: /data/pathogens/haemophilus_influenzae_tn106.fasta
 G49: /data/pathogens/helicobacter_pylori_26695.fasta
 G50: /data/pathogens/helicobacter_pylori_j99.fasta
 G51: /data/pathogens/klebsiella_pneumoniae_subsp_pneumoniae_1084.fasta
 G52: /data/pathogens/klebsiella_pneumoniae_subsp_pneumoniae_hs11286.fasta
 G53: /data/pathogens/klebsiella_pneumoniae_subsp_pneumoniae_ntuhk2044.fasta
 G54: /data/pathogens/legionella_pneumophila_subsp_pneumophila_str_philadelphia_1.fasta
 G55: /data/pathogens/listeria_innocua_slcc6294.fasta
 G56: /data/pathogens/listeria_monocytogenes_egde.fasta
 G57: /data/pathogens/mycobacterium_tuberculosis_h37rv.fasta
 G58: /data/pathogens/mycoplasma_hyopneumoniae_232.fasta
 G59: /data/pathogens/mycoplasma_pneumoniae_m129.fasta
 G60: /data/pathogens/neisseria_meningitidis_mc58.fasta
 G61: /data/pathogens/neisseria_meningitidis_z2491.fasta
 G62: /data/pathogens/pathogens.fasta
 G63: /data/pathogens/pseudomonas_aeruginosa_pa103.fasta
 G64: /data/pathogens/pseudomonas_aeruginosa_pao1.fasta
 G65: /data/pathogens/rickettsia_conorii_str_malish_7.fasta
 G66: /data/pathogens/salmonella_enterica_serovar_typhimurium.fasta
 G67: /data/pathogens/salmonella_enterica_subsp_enterica_serovar_typhi_str_ct18.fasta
 G68: /data/pathogens/salmonella_enterica_subsp_enterica_serovar_typhimurium_str_14028s.fasta
 G69: /data/pathogens/salmonella_enterica_subsp_enterica_serovar_typhimurium_str_lt2.fasta
 G70: /data/pathogens/shigella_dysenteriae_sd197.fasta
 G71: /data/pathogens/shigella_flexneri_2a_str_301.fasta
 G72: /data/pathogens/staphylococcus_aureus.fasta
 G73: /data/pathogens/staphylococcus_aureus_rn4220.fasta
 G74: /data/pathogens/staphylococcus_aureus_subsp_aureus_col.fasta
 G75: /data/pathogens/staphylococcus_aureus_subsp_aureus_mw2.fasta
 G76: /data/pathogens/staphylococcus_aureus_subsp_aureus_n315.fasta
 G77: /data/pathogens/staphylococcus_aureus_subsp_aureus_str_newman.fasta
 G78: /data/pathogens/streptococcus_agalactiae_2603vr.fasta
 G79: /data/pathogens/streptococcus_agalactiae_a909.fasta
 G80: /data/pathogens/streptococcus_agalactiae_fm027022.fasta
 G81: /data/pathogens/streptococcus_agalactiae_nem316.fasta
 G82: /data/pathogens/streptococcus_pneumoniae_r6.fasta
 G83: /data/pathogens/streptococcus_pneumoniae_taiwan19f14.fasta
 G84: /data/pathogens/streptococcus_pneumoniae_tigr4.fasta
 G85: /data/pathogens/streptococcus_pyogenes_m1_gas.fasta
 G86: /data/pathogens/streptococcus_pyogenes_mgas315.fasta
 G87: /data/pathogens/streptococcus_pyogenes_mgas5005.fasta
 G88: /data/pathogens/streptococcus_pyogenes_mgas8232.fasta
 G89: /data/pathogens/vibrio_cholerae_o1_biovar_el_tor_str_n16961.fasta
 G90: /data/pathogens/vibrio_parahaemolyticus.fasta
 G91: /data/pathogens/vibrio_parahaemolyticus_rimd_2210633.fasta
 G92: /data/pathogens/vibrio_vulnificus_cmcp6.fasta
 G93: /data/pathogens/vibrio_vulnificus_yj016.fasta
 G94: /data/pathogens/yersinia_enterocolitica_subsp_enterocolitica_8081.fasta
 G95: /data/pathogens/yersinia_enterocolitica_w1024.fasta
 G96: /data/pathogens/yersinia_pestis_co92.fasta
