configfile: "config_pathogens.yaml"

#rule all:
#	input:
#		"/home/ousmane.cisse/DATA/NCBI_hack/data/processed/VFDB/SRR8247573.nt.tab"
#	"../data/processed/VFDB/HMM/tmp.txt"

rule get_genes:
	input:
		setAnt ="../data/raw/VFDB/VFDB_setA_nt.fas", 
		setAprot="../data/raw/VFDB/VFDB_setA_pro.fas",
		setBnt="../data/raw/VFDB/VFDB_setB_nt.fas",
		setBprot="../data/raw/VFDB/VFDB_setB_pro.fas"
	output:
		setAnt="../data/processed/VFDB/setAnt.fas.Selected_Genes_info.txt",
		setAprot="../data/processed/VFDB/setApro.fas.Selected_Genes_info.txt",
		setBnt="../data/processed/VFDB/setA_pro.fas.Selected_Genes_info.txt",
		setBprot="../data/processed/VFDB/setB_pro.fas.Selected_Genes_info.txt"

#	conda:
#		"envs/meta.yaml"

	threads: 1

	run:
		shell("perl ../scripts/group_by_genes.pl {input.setAnt} > {output.setAnt}")
		shell("perl ../scripts/group_by_genes.pl {input.setAprot} > {output.setAprot}")
		shell("perl ../scripts/group_by_genes.pl {input.setBnt} > {output.setBnt}")
		shell("perl ../scripts/group_by_genes.pl {input.setBprot} > {output.setBprot}")

rule build_hmm:
	input:
		setAnt=rules.get_genes.output.setAnt,
		setAprot=rules.get_genes.output.setBprot,
		setBnt=rules.get_genes.output.setBnt,
		setBprot=rules.get_genes.output.setBprot,
		setAn="../data/raw/VFDB/VFDB_setA_nt.fas",
		setAp="../data/raw/VFDB/VFDB_setA_pro.fas",
		setBn="../data/raw/VFDB/VFDB_setB_nt.fas",
		setBp="../data/raw/VFDB/VFDB_setB_pro.fas",
	
	output:
		"../data/processed/VFDB/HMM/tmp.txt"

	run:
		#shell("echo > $output")
#		shell("perl ../scripts/buil_hmm.pl {input.setAnt} {input.setAn}")
#		shell("perl ../scripts/buil_hmm.pl {input.setAprot} {input.setAp}")
		shell("perl ../scripts/buil_hmm.pl {input.setBnt} {input.setBn}")
		shell("perl ../scripts/buil_hmm.pl {input.setBprot} {input.setBp}")



# randomly picked two for test
rule test_hmm:
	input:
		hmmP="/home/ousmane.cisse/DATA/NCBI_hack/data/processed/VFDB/VFDB_setA_pro.hmm",
		hmmN="/home/ousmane.cisse/DATA/NCBI_hack/data/processed/VFDB/VFDB_setA_nt.hmm",
		fasta=expand("sample=config["samples"]) 
#		t1="/data/SRP170931/spades_contigs/SRR8247572.fasta",
#		t2="/data/SRP170931/spades_contigs/SRR8247573.fasta"
	output:
		temp("/home/ousmane.cisse/DATA/NCBI_hack/data/processed/VFDB/pathogens/{sample}.tab")
#		t1="/home/ousmane.cisse/DATA/NCBI_hack/data/processed/VFDB/SRR8247572.nt.tab",
#		t2="/home/ousmane.cisse/DATA/NCBI_hack/data/processed/VFDB/SRR8247573.nt.tab"
	params:
		eval="1e-10"

	threads: 8
#	run:
#		shell("hmmsearch -E {params.eval} --cpu {threads} -Z 21154 --domtblout {output.t1} {input.hmmN} {input.t1}")
#		shell("hmmsearch -E {params.eval} --cpu {threads} -Z 21154 --domtblout {output.t2} {input.hmmN} {input.t2}")	
	shell:
		"hmmsearch -E {params.eval} --cpu {threads} --domtblout {output} {input.hmmN} {input.fasta}"
